services:
  - name: zhishangtanqiu-web
    type: web
    runtime: docker
    plan: starter
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /healthz
    autoDeployTrigger: commit
